# Generated by Django 3.0.5 on 2022-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_shortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswer',
            name='questionoption',
            field=models.CharField(max_length=200),
        ),
    ]
