# Generated by Django 3.0.5 on 2022-09-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20220921_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortquestion',
            name='prepostoption',
            field=models.CharField(default='Prequestion', max_length=200),
            preserve_default=False,
        ),
    ]
