# Generated by Django 3.0.5 on 2022-09-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
    ]
