# Generated by Django 3.0.5 on 2022-09-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Info',
        ),
    ]
