# Generated by Django 3.0.5 on 2022-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20220921_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info',
            field=models.CharField(max_length=5000),
        ),
    ]
